### ISSUE TITLE
Struggling with multi-master with external DB

### ISSUE THREAD

**Issue by thisisbenwoo** [alexellis/k3sup#325] opened 2021-04-30 03:17 UTC
I've used k3sup to deploy a number of different clusters for learning purposes. Now, I want to try using an external SQL database to achieve a multi-master setup. I have a MariaDB set up as a Docker container. However, I can't seem to get it to work. For the purposes of illustration, I'm going to make it very simple:
Mysql user: k3sup
Mysql password: k3sup
Mysql database: k3sup
Docker IP for the MariaDB container
Linux user: me 
SERVER1: 10.10.10.1

Following the README.md, I did the following export:
`export DATASTORE=mysql://k3sup:k3sup@tcp(192.168.1.1:3306)/k3sup`

Then I did:
`k3sup install --user me --ip $SERVER1 --datastore="${DATASTORE}"`

I keep getting the following error when I do a `systemctl status k3s.service`
`Process: 18237 ExecStart=/usr/local/bin/k3s server --tls-san 10.10.10.1 --datastore-endpoint mysql://k3sup:k3sup@tcp(192.168.1.1:3306)/k3sup (code=exited
Main PID: 20770 (code=exited, status=1/FAILURE)`

## Expected Behaviour

This should set up my first server on SERVER1

## Current Behaviour

It keeps failing and k3s never comes up

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

I cannot get the first server to start up.

## Your Environment

* What Kubernetes distribution are you using?
* 

```
kubectl version
W0429 20:13:13.193300   24009 loader.go:223] Config not found: /home/me/kube_config_cluster.yml
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
Ubuntu 20.04.2 LTS on bare metal
Hosted locally
MariaDB in a Docker container

* Operating System and version (e.g. Linux, Windows, MacOS):
* Linux Ubuntu 20.04.2 LTS

```
uname -a
Linux server 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

## "Be part of the solution"

Subject to approval, are you willing to work on a Pull Request for this issue or feature request?

Yes/No
Yes, but I'll need a little hand-holding!
## Are you a GitHub Sponsor (Yes/No?)

https://github.com/sponsors/alexellis

**Comment by alexellis** [comment] 2021-05-13 20:16
Hi @thisisbenwoo 

We can't provide technical support for your environment. I'm sorry about that, but k3sup receives no sponsorship and you are also not a sponsor.

This feature works and has been tested. If you can provide a reproduction with postgresql or mysql, then we could potentially explore it further.

I'm going to close this, but if we see more reports of mysql or postgresql (both documented in the README) as not working, then I'll take a look into it myself.

For now, I can point you to MySQL and etcd:

* https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-external-sql
* https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-embedded-etcd

You should also pay specific attention to the logs from k3s.

Alex

**Closed by alexellis** 2021-05-13 20:16 UTC

**Comment by thisisbenwoo** [comment] 2021-05-13 20:34
Thanks Alex, I understand. 



---

BenWoo | +1 (212) ***@***.***
On 5/13/2021 13:16:28, Alex Ellis ***@***.***> wrote:
Hi @thisisbenwoo [https://github.com/thisisbenwoo]
We can't provide technical support for your environment. I'm sorry about that, but k3sup receives no sponsorship and you are also not a sponsor.
This feature works and has been tested. If you can provide a reproduction with postgresql or mysql, then we could potentially explore it further.
I'm going to close this, but if we see more reports of mysql or postgresql (both documented in the README) as not working, then I'll take a look into it myself.
For now, I can point you to MySQL and etcd:
* https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-external-sql [https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-external-sql]
* https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-embedded-etcd [https://github.com/alexellis/k3sup#create-a-multi-master-ha-setup-with-embedded-etcd]
You should also pay specific attention to the logs from k3s.
Alex

**Comment by alexellis** [comment] 2021-05-13 20:43
If it helps, I added a note about k3s support in the README and said that users need to contact Rancher, not me if they find issues in K3s.

K3sup is an installer for K3s. I am sympathetic, but it's (effectively) only Rancher that can fix issues in K3s. 

https://github.com/alexellis/k3sup#troubleshooting

When is it time to raise an issue for k3sup? When it configures k3s incorrectly. And it seems to be writing the data connection string correctly. I just tried it out on a Linode box and the command line looked as expected.

**Comment by thisisbenwoo** [comment] 2021-05-13 20:44
Understood. You've been very generous in giving me these tips.


Please stay safe!

b
---
BenWoo | +1 (212) ***@***.*** [http://gmail.com]
On 5/13/2021 13:43:45, Alex Ellis ***@***.***> wrote:
If it helps, I added a note about k3s support in the README and said that users need to contact Rancher, not me if they find issues in K3s.
K3sup is an installer for K3s. I am sympathetic, but it's (effectively) only Rancher that can fix issues in K3s.
https://github.com/alexellis/k3sup#troubleshooting [https://github.com/alexellis/k3sup#troubleshooting]
When is it time to raise an issue for k3sup? When it configures k3s incorrectly. And it seems to be writing the data connection string correctly. I just tried it out on a Linode box and the command line looked as expected.

**Comment by alexellis** [comment] 2021-05-13 20:48
We tested with MySQL on DigitalOcean, so I can't speak for what you're using, but this may be related:

https://github.com/k3s-io/k3s/issues/1805

**Comment by alexellis** [comment] 2021-05-13 20:50
May also be related: https://github.com/k3s-io/k3s/issues/1153

**Comment by alexellis** [comment] 2021-05-13 20:58
This worked exactly as expected with DigitalOcean

```
alex@alex-nuc8:~$ k3sup install --ip 139.162.242.248 --user root --datastore "mysql://doadmin:gz5jntxxfce2wyir@tcp(db-mysql-lon1-91545-do-user-2197152-0.b.db.ondigitalocean.com:25060)/defaultdb"
Running: k3sup install
2021/05/13 21:56:17 139.162.242.248
Public IP: 139.162.242.248
[INFO]  Finding release for channel v1.19
[INFO]  Using v1.19.10+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.19.10+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  No change detected so skipping service start
Result: [INFO]  Finding release for channel v1.19
[INFO]  Using v1.19.10+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.19.10+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
[INFO]  No change detected so skipping service start
 Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.

Saving file to: /home/alex/kubeconfig

# Test your cluster with:
export KUBECONFIG=/home/alex/kubeconfig
kubectl config set-context default
kubectl get node -o wide
alex@alex-nuc8:~$ export KUBECONFIG=/home/alex/kubeconfig
alex@alex-nuc8:~$ kubectl config set-context default
Context "default" modified.
alex@alex-nuc8:~$ kubectl get node -o wide
NAME        STATUS   ROLES    AGE   VERSION         INTERNAL-IP       EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
localhost   Ready    master   17s   v1.19.10+k3s1   139.162.242.248   <none>        Ubuntu 21.04   5.11.0-16-generic   containerd://1.4.4-k3s1
alex@alex-nuc8:~$ 
```

The database was deleted after, I have deliberately leaked the password.

Perhaps the database version or variant you are using is not supported. 

Certified versions are explained here: https://rancher.com/docs/k3s/latest/en/installation/datastore/

cc @rgee0
