### ISSUE TITLE
Add delete cluster command de k3sup CLI

### ISSUE THREAD

**Issue by abousselmi** [alexellis/k3sup#236] opened 2020-05-06 15:45 UTC
I need to be able de remove a running (local or remote) k3s cluster. I suggest adding a command to k3sup CLI.

## Expected Behaviour

It should be something like:

```sh
k3sup delete -c $HOME/kubeconfig
```

The result is a deleted k3s cluster.

## Current Behaviour

The command does not exist.

## Possible Solution

Add the command to the k3sup CLI

## Steps to Reproduce (for bugs)

```sh
k3sup
```

No delete cluster command.

## Context

It should help with removing in a quicker way the already running clusters.

**Comment by Amalkh5** [comment] 2020-05-07 21:30
@abousselmi I opened PR  #241 that will add the command.

**Comment by abousselmi** [comment] 2020-05-11 10:07
@Amalkh5 nice !

**Comment by alexellis** [comment] 2020-05-11 10:08
Derek close: duplicate of #106

**Closed by alexellis** 2020-05-11 10:08 UTC
