### ISSUE TITLE
[feature]sudo on user support?

### ISSUE THREAD

**Issue by sokoow** [alexellis/k3sup#79] opened 2019-10-31 17:57 UTC
Hey Alex,

Great work as usually, really impressive project :) What about adding sudoed user to bootstrap options ? Currently only root can install k3sup..

**Comment by alexellis** [comment] 2019-10-31 18:16
Thank you that's really kind. 

Please could you go back and fill out the whole issue template along with any errors you are seeing and how we can reproduce this?

**Comment by alexellis** [comment] 2019-11-30 22:56
Closing due to lack of information. @sokoow you can run the install bash script as a normal user, I'm not sure what you meant, feel free to come back later and enlighten us.

**Closed** 2019-11-30 22:55 UTC
