### ISSUE TITLE
Feature Request / Discussion : Using SSH config file

### ISSUE THREAD

**Issue by webtroter** [alexellis/k3sup#400] opened 2023-01-24 20:32 UTC
Could k3sup use the user's ssh_config when connecting to remote servers?

## Why do you need this?

My network is so secure it doesn't allow SSH to the Internet, so I use a SSH Proxy. All this is configured in my ssh_config, using ProxyJump

Also, my SSH Key is stored on my Yubikey (using id-rsa format, no the FIDO one), and k3sup doesn't support it.

```
# ssh_config excerpt

Host *.ovh.sslip.io
    ProxyJump BHS1-Rebond
    IdentityFile ~/.ssh/id_rsa_y5
    User cloud_user
Host BHS1-Rebond
    Hostname ovh-rebond-unix1.redacted.com
    User webtroter
    HostKeyAlgorithms ssh-rsa
    IdentityFile ~/.ssh/id_rsa_y5
    PubkeyAcceptedKeyTypes +ssh-rsa

```

## Expected Behaviour
k3sup should check and use the existing ssh_config for the target if it exists.

## Current Behaviour
k3sup seems to completely ignore the ssh_config

## Possible Solution
Not sure

## Steps to Reproduce
Configure your ssh_config, test the config using ssh, then try to install k3s with k3sup

## Your Environment

* k3sup version:

```
k3sup version
[...]
Version: 0.12.12
Git Commit: 02c7a775b9914b9dcf3b90fa7935eb347b7979e7
```

* What Kubernetes distribution, client and server version are you using?

N/A

* What OS or type or VM are you using for your cluster? Where is it hosted? (for `k3sup install/join`):
RockyLinux in this case. Not sure what is the underlying provider (maybe aws)

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Client/Controller side :  Windows 11 Pro
```

## Do you want to work on this?

Subject to design approval, are you willing to work on a Pull Request for this issue or feature request?

- [ ] Yes
- [x] No

**Comment by alexellis** [comment] 2023-01-26 12:53
Thanks for your interest. This kind of feature will be subscription only. It is on the roadmap, so stay tuned for an update.

I'm going to close this for now as a duplicate of other requests we've had for jump boxes.

Stay tuned.

Alex

**Comment by alexellis** [comment] 2023-01-26 12:53
/set title: [Feature request] Jump box support

**Closed by alexellis** 2023-01-26 12:53 UTC
