### ISSUE TITLE
SSH error while trying to combine IPs to the master node for a cluster server. 

### ISSUE THREAD

**Issue by CoreyCBurton** [alexellis/k3sup#319] opened 2021-04-10 04:44 UTC
I have installed K3sup on all four of my raspberry Pis and initiated the master node with the command 
`k3sup install --ip <master node> --user ubuntu`
While running the command to add other nodes to this cluster I get an error validating SSH. 

## Expected Behaviour

When I type in the command 
`k3sup join --ip 192.168.1.141 --server-ip 192.168.1.96 --user ubuntu --ssh-key .ssh/id_rsa`
It is suppose to connect to the network and add it as a new node.
## Current Behaviour

I get an error that states
`Error: unable to connect to 192.168.1.141:22 over ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

## Context

I am trying to add all 4 Raspberry Pis to one cluster.
## Your Environment

* What Kubernetes distribution are you using?

Ubuntu Server 20.04 LTS

**Comment by alexellis** [comment] 2021-04-10 22:00
Hi, you need to run `ssh-copy-id ubuntu@192.168.1.141` before running `k3sup join`.

Please feel free to read the instructions in the README for examples 👍 

I'll close this, but feel free to keep commenting and we'll re-open it, if there's an issue that can be reproduced. The join command is very well tested at this point and I'm not aware of any issues with it.

Alex

**Closed by alexellis** 2021-04-10 22:00 UTC

**Comment by CoreyCBurton** [comment] 2021-04-11 01:15
Thank you! The ssh-copy-id worked and I have the cluster set up. The problem now is that when I use this command to export `export KUBECONFIG=/home/ubuntu/kubeconfig` and `kubectl get nodes -o wide`
I get this error 
`The connection to the server 192.168.1.98:6443 was refused - did you specify the right host or port?`

**Comment by alexellis** [comment] 2021-04-11 08:07
Sounds like you may have misconfigured your Ubuntu host so that K3s won't start. To see what went wrong, type in `sudo journactl -u k3s`

You need to update /boot/cmdline.txt or /boot/firmware/cmdline.txt and add the lines from the K3sup readme. This is what we do for Raspberry Pi OS: https://github.com/alexellis/k3sup#-micro-tutorial-for-raspberry-pi-2-3-or-4-

**Comment by azzarello** [comment] 2021-09-20 18:09
@alexellis So I am having the same issue on a SERVER based on Raspbian Lite, I used the `ssh-copy-id` like you mention above and it skips since I have already done it. I can manually connect via `ssh IP`, but the `k3sup join ...` command fails for the same reason as the OP. Any suggestions would be appreciated!
