### ISSUE TITLE
Error when setting --k3s-extra-args for agents

### ISSUE THREAD

**Issue by bgulla** [alexellis/k3sup#30] opened 2019-09-02 18:51 UTC
After setting an `--k3s-extra-args='--docker'` flag in the master install, future created kubelets/ agent-nodes do not automatically inherit the flags. Additionally, passing the flag during agent creation results in an error.

## Expected Behaviour

I would assume that agents would inherit the extra args set at master creation. Even though the do no inherit the flags, setting them via the `k3sup join` command results in an error. 

## Current Behaviour

Agent nodes do not inherit the `--k3s-extra-args` set at master creation. Setting `--k3s-extra-args='--docker'` results in an error. 

## Steps to Reproduce (for bugs)

1. `k3sup join --ip $AGENT_IP --server-ip $SERVER_IP --user $USER --k3s-extra-args="--docker"`
2. results in `curl -sfL https://get.k3s.io/ | K3S_URL="https://10.0.1.78:6443" K3S_TOKEN="<redacted_token>::node:<redacted>" sh - --docker` --> `sh: 0: Can't open --docker`

## Context

I would like to have k3s run as docker instead of containerd so that I can use cAgent monitoring tools.

## Your Environment
**Master** - Jetson Nano- L4T-ubuntu - `Kernel: 4.9.140` - `docker://18.9.7`
**Agents** - RaspberryPi-4 4gb Buster Debian - `Kernel:4.19.57-v7l+` - `containerd://1.2.7-k3s1`
**K3sup** - `Version: 0.2.4`

**Comment by alexellis** [comment] 2019-09-08 08:31
> Agent nodes do not inherit the --k3s-extra-args set at master creation. 

This is as designed and would not be the case since `k3sup` is not stateful.

> Setting --k3s-extra-args='--docker' results in an error.

This is not as designed :disappointed: let me ping the author of that PR. 

@billimek it looks like your PR may not be working for agents, please could you provide a fix for this? @bgulla has provided instructions above.

@bgulla alternatively, if you want to send a PR to fix the join command formatting, then go ahead :-)

Thanks,

Alex

**Comment by billimek** [comment] 2019-09-08 22:35
I think I see the problem.

In the installation curl command, we do:

```golang
fmt.Sprintf("curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server --tls-san %s %s' sh -\n", ip, k3sExtraArgs)
```

while in the join curl command, we do:

```golang
fmt.Sprintf(`curl -sfL https://get.k3s.io/ | K3S_URL="https://%s:6443" K3S_TOKEN="%s" sh - %s`, serverIP.String(), strings.TrimSpace(joinToken), k3sExtraArgs)
```

It's very subtle, but the `k3sExtraArgs` variable subst should happen _before_ the `sh -`.  I think I know what to change and test.  Please stand by!

**Closed** 2019-09-16 10:59 UTC
Labels: design/approved
